### ISSUE TITLE
Model checkpoints for inference

### ISSUE THREAD

**Issue by kumar-devesh** [zengqunzhao/DFER-CLIP#2]
Thanks for releasing the code! Do you plan to make trained model checkpoints available for inference?

**Comment by zengqunzhao** [comment]
> Thanks for releasing the code! Do you plan to make trained model checkpoints available for inference?

Hi, please see the checkpoints here: 
https://github.com/zengqunzhao/DFER-CLIP/tree/main?tab=readme-ov-file#test-pre-trained-models
