### ISSUE TITLE
IndexError: list index out of range; seg_imgs = [Image.open(os.path.join(video_frames_path[p])).convert('RGB')]

### ISSUE THREAD

**Issue by DuNGEOnmassster** [zengqunzhao/DFER-CLIP#3]
Failed to run on MAFW dataset with train_MAFW.sh

<img width="888" alt="image" src="https://github.com/zengqunzhao/DFER-CLIP/assets/95074892/063e3f0b-321b-4ea4-80c1-0a0f8b417595">

**Comment by zengqunzhao** [comment]
> Failed to run on MAFW dataset with train_MAFW.sh
> 
> <img alt="image" width="888" src="https://private-user-images.githubusercontent.com/95074892/318715304-063e3f0b-321b-4ea4-80c1-0a0f8b417595.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyNDk3NjQsIm5iZiI6MTcxMjI0OTQ2NCwicGF0aCI6Ii85NTA3NDg5Mi8zMTg3MTUzMDQtMDYzZTNmMGItMzIxYi00ZWE0LTgwYzEtMGEwZjhiNDE3NTk1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDE2NTEwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlYzljZmRhZDFiYWExYjE2M2Y3OGI0NDEzZmJkYzcyYzBlOGUxNzUwNzAxNWIxNTY2YjBmYzUyMzlkNTQxZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.vCR7rzXJdzUmNd64lNDVP3xZbs9nGf5KjkN5Vf5P_RI">

Hi, seems the videos were not loaded successfully, check your dataset path and annotations files.
